# Generated by Django 4.2.11 on 2024-03-27 15:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="chat_type",
            field=models.SmallIntegerField(
                choices=[("user", "question"), ("chatcar", "answer")],
                verbose_name="对话类型",
            ),
        ),
    ]
